name: LabsNickTool
main: de.bergwerklabs.framework.nick.de.bergwerklabs.nick.LabsNickPlugin
website: http://www.bergwerklabs.de
author: Freggy
version: 1.0
depend: [LabsFrameworkSpigotCommons]

commands:
    nick:
    nicklist: